version: "3.8"

services:
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - shared_backend
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  shared_backend:
    external: true
