services:

  mysql:
#    image: mysql:8.0
#    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0-bookworm
#    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: sasa
    ports:
      - 8306:3306
    volumes:
      - /docker/mysql:/var/lib/mysql
    networks:
      - default
    deploy:
      placement:
        constraints:
          - node.role == manager
#		  
# restart no es compatible con Swarm (que es lo que usa docker stack deploy).
# Hay que confiar en la sección deploy: para manejar la replicación, reinicio, etc.
#    restart: always

  facturascripts:
    image: facturascripts/facturascripts:latest
    ports:
#
#      - 80:80
#
      - 8081:80
    volumes:
      - /docker/facturascripts:/var/www/html
    networks:
      - default
      - traefik_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.facturascripts.rule=Host(`cortinascristobal-fs.duckdns.org`)"
        - "traefik.http.routers.facturascripts.entrypoints=websecure"
        - "traefik.http.routers.facturascripts.priority=1"
        - "traefik.http.routers.facturascripts.tls.certresolver=le"
        - "traefik.http.routers.facturascripts.service=facturascripts"
        - "traefik.http.services.facturascripts.loadbalancer.server.port=80"
    depends_on:
      - mysql
#    restart: always

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - default
    deploy:
      placement:
        constraints:
          - node.role == manager
#    restart: always

networks:
  traefik_public:
    external: true
