version: "3.8"

services:
  facturascripts:
    image: facturascripts/facturascripts:latest
    ports:
#      - 80:80
      - 8081:80
    volumes:
      - /docker/facturascripts:/var/www/html
      - /docker/sh_creados/wait-for-mysql.sh:/usr/local/bin/wait-for-mysql.sh
# El contenedor de facturascripts no tiene sh instalado, sino bash
# por lo que no usaremos
#    entrypoint: ["/bin/sh", "/usr/local/bin/wait-for-mysql.sh"]
#usaremos
    entrypoint: ["/bin/bash", "/usr/local/bin/wait-for-mysql.sh"]
    networks:
      - shared_backend
      - traefik_public
    #environment:
      #- DATABASE_HOST=mysql
      #- DATABASE_PORT=3306
      #- DATABASE_USER=root
      #- DATABASE_PASSWORD=sasa
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.facturascripts.rule=Host(`cortinascristobal-fs.duckdns.org`)"
        - "traefik.http.routers.facturascripts.entrypoints=websecure"
        - "traefik.http.routers.facturascripts.priority=1"
        - "traefik.http.routers.facturascripts.tls.certresolver=le"
        - "traefik.http.routers.facturascripts.service=facturascripts"
        - "traefik.http.services.facturascripts.loadbalancer.server.port=80"

networks:
  shared_backend:
    external: true
  traefik_public:
    external: true
