services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Postgres connection parameters:
      # DB_POSTGRES_HOST: 'db'
      # DB_POSTGRES_PORT: '5432'
      # DB_POSTGRES_USER: 'npm'
      # DB_POSTGRES_PASSWORD: 'npmpass'
      # DB_POSTGRES_NAME: 'npm'
      # 
      # Mysql/Maria connection parameters:
      # DB_MYSQL_HOST: "db"
      # DB_MYSQL_PORT: 3306
      # DB_MYSQL_USER: "npm"
      # DB_MYSQL_PASSWORD: "npm"
      # DB_MYSQL_NAME: "npm"
      # 
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      DB_SQLITE_FILE: "/data/database.sqlite"
      # 
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'    
    volumes:
      - /docker/nginx/data:/data
      - /docker/nginx/etc/letsencrypt:/etc/letsencrypt
    # depends_on:
    #   - db

  # db:
    # If Select Mysql/Maria
    # image: 'jc21/mariadb-aria:latest'
    # restart: always
    # environment:
      # MYSQL_ROOT_PASSWORD: 'npm'
      # MYSQL_DATABASE: 'npm'
      # MYSQL_USER: 'npm'
      # MYSQL_PASSWORD: 'npm'
      # MARIADB_AUTO_UPGRADE: '1'
    # volumes:
      # - /docker/mysql/var/lib/mysql:/var/lib/mysql

    # If Select Postgres
    # image: postgres:latest
    # restart: always
    # environment:
      # POSTGRES_USER: 'npm'
      # POSTGRES_PASSWORD: 'npmpass'
      # POSTGRES_DB: 'npm'
    # volumes:
      # - /docker/postgres/var/lib/postgresql/data:/var/lib/postgresql/data
