#--------------------#
# wgEasy = Wireguard #
#--------------------#

version: "3.8"

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    environment:
      - PUID=1000
      - PGID=1000
      #
      # 丘멆잺 Change the server's hostname (clients will connect to):
      - WG_HOST=cortinascristobal-wg.duckdns.org
      #
      # 丘멆잺 Change the Web UI Password:
      # - PASSWORD=OrJe0Wgeasy  #  Desde la versi칩n v14 de wg-easy, ya no se permite usar la variable de entorno PASSWORD en texto plano por motivos de seguridad. Ahora es obligatorio usar PASSWORD_HASH, que debe contener una contrase침a en formato hash bcrypt.
      - PASSWORD_HASH="$2b$10$I.53Sx0bdGpjbBEbWCgtqO3bRu69bi5slA0KVTsVFXBQc113dsoSK"
      #
      # 游눠 This is the Pi-Hole Container's IP Address
      #
      # --------------------------------------------------
      # La IA me recomienda modificar la siguientes l칤neas
      # --------------------------------------------------
      #- WG_DEFAULT_DNS=10.8.1.3  #  Ya no necesitas la IP est치tica de Pi-hole, porque Docker Swarm se encargar치 de resolver pihole a su IP interna autom치ticamente.
      #- WG_DEFAULT_ADDRESS=10.8.0.x  #  WG_DEFAULT_ADDRESS define el rango de direcciones IP internas que los clientes de WireGuard recibir치n al conectarse
                                      #  NO es v치lida. Esa variable requiere una direcci칩n v치lida o un rango de direcciones, no puede tener una x como comod칤n.	  
      # --------------------------------------------------
      - WG_DEFAULT_DNS=pihole
      #- WG_DEFAULT_ADDRESS=10.8.0.0/24  #  Esta opci칩n (/24) es mejor si piensas tener varios clientes.
      - WG_DEFAULT_ADDRESS=10.8.0.x
      # --------------------------------------------------
      #
    #
    # --------------------------------------------------
    # container_name no es compatible con Docker Swarm
    # --------------------------------------------------
    #container_name: wg-easy
    # --------------------------------------------------
    #
    volumes:
      - /docker/wgeasy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    #
    # -----------------------------------------------------
    # Si estamos bajo docker swarm no hace falta el restart
    # -----------------------------------------------------
    #restart: unless-stopped
    # -----------------------------------------------------
    #
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - traefik_public
      #
      # ---------------------------------------------------------------------------
      # Docker Swarm no permite asignar IPs est치ticas directamente en contenedores.
      # Las secciones como esta no funcionar치n en Swarm
      # ---------------------------------------------------------------------------
      #wg-easy:
        #ipv4_address: 10.8.1.2
      # ---------------------------------------------------------------------------
      #
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wg-easy.rule=Host(`cortinascristobal-wg.duckdns.org`)"
        - "traefik.http.routers.wg-easy.entrypoints=websecure"
        #
        # -----------------------------------------------------
        # Curiosamente la siguiente l칤nea me la quit칩 la IA
        # -----------------------------------------------------
        - "traefik.http.routers.wg-easy.priority=1"
        # -----------------------------------------------------
        #
        - "traefik.http.routers.wg-easy.tls.certresolver=le"
        #
        # -----------------------------------------------------
        # Curiosamente la siguiente l칤nea me la quit칩 la IA
        # -----------------------------------------------------
        - "traefik.http.routers.wg-easy.service=wg-easy"
        # -----------------------------------------------------
        #
        - "traefik.http.services.wg-easy.loadbalancer.server.port=51821"

networks:
  traefik_public:
    external: true
  shared_backend:
    external: true
  #
  # ---------------------------------------------------------------------------
  # Docker Swarm no permite asignar IPs est치ticas directamente en contenedores.
  # Las secciones como esta no funcionar치n en Swarm
  # ---------------------------------------------------------------------------
  #wg-easy:
    #ipam:
      #config:
        #- subnet: 10.8.1.0/24
  # ---------------------------------------------------------------------------
  #
